name: CI/CD Pipeline

on:
  push:
    branches-ignore:
      - dev
      - main

  pull_request:
    branches:
      - dev
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  build-test-feature:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      - name: Run tests
        run: |
          echo "Running tests..."
          # pytest --maxfail=1 --disable-warnings -q

  build-push-artifact:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker image
        id: build-image
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" = "dev" ]; then
            export DEPLOY_ENV="dev"
          else
            export DEPLOY_ENV="prod"
          fi
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas-app-$DEPLOY_ENV:${{ github.sha }} .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Push Docker image
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" = "dev" ]; then
            export DEPLOY_ENV="dev"
          else
            export DEPLOY_ENV="prod"
          fi
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas-app-$DEPLOY_ENV:${{ github.sha }}

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Determine artifact tag
        id: artifact
        run: |
          DEPLOY_ENV="${{ github.event.inputs.environment }}"
          if [ "$DEPLOY_ENV" = "dev" ]; then
            IMAGE_TAG="gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas-app-dev:latest"
          else
            IMAGE_TAG="gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas-app-prod:latest"
          fi
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
