name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          # (Replace with your test command, e.g., pytest)
          echo "No tests defined yet"

  build-deploy:
    name: Build, Containerize and Deploy to GCP App Engine
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/saas-app:$GITHUB_SHA .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Push Docker Image to Google Container Registry
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/saas-app:$GITHUB_SHA

      - name: Deploy to GCP App Engine
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
